name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        cache-dependency-path: src/package-lock.json
        node-version: 20
        cache: 'npm'
    - working-directory: ./src
    - name: Install dependencies
      run: | 
        echo $PWD
        npm install
        npm run build
        ls
