name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy-and-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        cache-dependency-path: src/package-lock.json
        node-version: 20
        cache: 'npm'
    - name: Install dependencies
      run: | 
        npm install
        npm run build
      working-directory: ./src
    - name: Deploy to SFTP server
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: ${{ secrets.FTP_USERNAME }}
        server: ${{ secrets.FTP_SERVER }}
        port: ${{ secrets.FTP_PORT }}
        local_path: './src/dist/*'
        remote_path: '/'
        sftp_only: true
        password: ${{ secrets.FTP_PASSWORD }}
    
